web/router.ex
defmodule Mousikin.Router do
  use Mousikin.Web, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser
    coherence_routes
  end

  scope "/", Mousikin do
    pipe_through :browser
    get "/", PageController, :index
    # Add public routes below
    resources "/artists", ArtistController
    resources "/albums", AlbumController
  end

  scope "/", Mousikin do
    pipe_through :protected
    # Add protected routes below
    #resources "/artists", ArtistController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Mousikin do
  #   pipe_through :api
  # end
end

web/views/coherence/layout_view.ex
defmodule Coherence.LayoutView do
  use Mousikin.Coherence.Web, :view


end

web/views/layout_view.ex
defmodule Mousikin.LayoutView do
  use Mousikin.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Mousikin!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
            <li><%= link "Artists", to: artist_path(@conn, :index) %></li>
            <li><%= link "Albums", to: album_path(@conn, :index) %></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>